"""removed col from student 2

Revision ID: 0dbcac9444be
Revises: e6cf3ab074fc
Create Date: 2021-01-13 09:18:22.950200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0dbcac9444be'
down_revision = 'e6cf3ab074fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'roll_no')
    op.drop_column('student', 'registration_no')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('registration_no', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('roll_no', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
