"""username and password added

Revision ID: 17dfa0252c2d
Revises: 2db349c0c5fb
Create Date: 2021-01-12 09:00:43.149174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17dfa0252c2d'
down_revision = '2db349c0c5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password', sa.String(length=512), nullable=False))
    op.add_column('student', sa.Column('username', sa.String(length=512), nullable=False))
    op.create_index(op.f('ix_student_mobile_no'), 'student', ['mobile_no'], unique=True)
    op.add_column('teacher', sa.Column('password', sa.String(length=512), nullable=False))
    op.add_column('teacher', sa.Column('username', sa.String(length=512), nullable=False))
    op.create_index(op.f('ix_teacher_mobile_no'), 'teacher', ['mobile_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_mobile_no'), table_name='teacher')
    op.drop_column('teacher', 'username')
    op.drop_column('teacher', 'password')
    op.drop_index(op.f('ix_student_mobile_no'), table_name='student')
    op.drop_column('student', 'username')
    op.drop_column('student', 'password')
    # ### end Alembic commands ###
