"""fresh2

Revision ID: 1ee24933b4db
Revises: 2d125a76bb92
Create Date: 2021-01-08 19:18:32.874011

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ee24933b4db'
down_revision = '2d125a76bb92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_route_bus_id'), 'bus_route', ['bus_id'], unique=False)
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=6), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('NET_BANKING', 'DEBIT_CARD', 'CREDIT_CARD', 'OFFLINE', name='paymentmode'), nullable=False),
    sa.Column('months', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_transaction_student_id'), 'fee_transaction', ['student_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'HALF_DAY', 'PRESENT', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    op.create_table('teacher_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'HALF_DAY', 'PRESENT', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_attendance_teacher_id'), 'teacher_attendance', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_attendance_teacher_id'), table_name='teacher_attendance')
    op.drop_table('teacher_attendance')
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_fee_transaction_student_id'), table_name='fee_transaction')
    op.drop_table('fee_transaction')
    op.drop_table('fee_structure')
    op.drop_index(op.f('ix_bus_route_bus_id'), table_name='bus_route')
    op.drop_table('bus_route')
    # ### end Alembic commands ###
