"""modified section

Revision ID: 2db349c0c5fb
Revises: a979ff86f3b2
Create Date: 2021-01-09 10:41:15.197273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2db349c0c5fb'
down_revision = 'a979ff86f3b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_section_numeric', table_name='section')
    op.drop_column('section', 'numeric')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('section', sa.Column('numeric', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_section_numeric', 'section', ['numeric'], unique=True)
    # ### end Alembic commands ###
