"""add joining

Revision ID: 351bd2b9f810
Revises: 27dd7f7878d1
Create Date: 2021-01-12 09:38:57.190945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '351bd2b9f810'
down_revision = '27dd7f7878d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('joining_date', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'joining_date')
    # ### end Alembic commands ###
