"""added col from student 2

Revision ID: 407bfff6f49d
Revises: 0dbcac9444be
Create Date: 2021-01-13 09:18:51.758206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407bfff6f49d'
down_revision = '0dbcac9444be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('registration_no', sa.String(length=255), nullable=False))
    op.add_column('student', sa.Column('roll_no', sa.String(length=255), nullable=True))
    op.create_unique_constraint(None, 'student', ['registration_no'])
    op.create_unique_constraint(None, 'student', ['roll_no'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'roll_no')
    op.drop_column('student', 'registration_no')
    # ### end Alembic commands ###
