"""added message

Revision ID: 9b0e78e9e1d6
Revises: f768337fc82a
Create Date: 2021-01-16 11:56:28.993678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b0e78e9e1d6'
down_revision = 'f768337fc82a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('receiver_role', sa.Enum('ADMIN', 'TEACHER', 'STUDENT', name='userrole'), nullable=False),
    sa.Column('message', sa.String(length=2048), nullable=False),
    sa.Column('is_broadcast', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_receiver_id'), 'message', ['receiver_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_receiver_id'), table_name='message')
    op.drop_table('message')
    # ### end Alembic commands ###
