"""remove user pass

Revision ID: a634bdefdeb1
Revises: 351bd2b9f810
Create Date: 2021-01-12 09:44:32.252579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a634bdefdeb1'
down_revision = '351bd2b9f810'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'username')
    op.drop_column('teacher', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('username', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
