"""fresh

Revision ID: a979ff86f3b2
Revises: 
Create Date: 2021-01-08 23:15:45.085317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a979ff86f3b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file', sa.String(length=512), nullable=True),
    sa.Column('text', sa.String(length=5000), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_route',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=128), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bus_route_bus_id'), 'bus_route', ['bus_id'], unique=False)
    op.create_table('classes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=6), nullable=False),
    sa.Column('numeric', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=True)
    op.create_index(op.f('ix_classes_numeric'), 'classes', ['numeric'], unique=True)
    op.create_table('enquiry',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_name', sa.String(length=512), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('father_name', sa.String(length=512), nullable=False),
    sa.Column('interested_class', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_structure',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_name', sa.String(length=6), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('library',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('book_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teacher',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('designation', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('religion', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=20), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('joining_date', sa.Date(), nullable=False),
    sa.Column('photo', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('head_teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=6), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.Column('numeric', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['head_teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=True)
    op.create_index(op.f('ix_section_numeric'), 'section', ['numeric'], unique=True)
    op.create_table('teacher_time_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_1', sa.String(length=64), nullable=True),
    sa.Column('class_2', sa.String(length=64), nullable=True),
    sa.Column('class_3', sa.String(length=64), nullable=True),
    sa.Column('class_4', sa.String(length=64), nullable=True),
    sa.Column('remaining_slots', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_time_table_teacher_id'), 'teacher_time_table', ['teacher_id'], unique=False)
    op.create_table('student',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('registration_no', sa.String(length=255), nullable=False),
    sa.Column('roll_no', sa.String(length=255), nullable=True),
    sa.Column('father_name', sa.String(length=255), nullable=True),
    sa.Column('mother_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='gendertype'), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('religion', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile_no', sa.String(length=32), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('pin_code', sa.String(length=255), nullable=False),
    sa.Column('photo_path', sa.String(length=512), nullable=True),
    sa.Column('tc_path', sa.String(length=512), nullable=True),
    sa.Column('migration_path', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_transaction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('session', sa.String(length=10), nullable=False),
    sa.Column('transaction_date', sa.DateTime(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.Enum('NET_BANKING', 'DEBIT_CARD', 'CREDIT_CARD', 'OFFLINE', name='paymentmode'), nullable=False),
    sa.Column('months', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_transaction_student_id'), 'fee_transaction', ['student_id'], unique=False)
    op.create_table('solution',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('solution_file', sa.String(length=512), nullable=True),
    sa.Column('comment', sa.String(length=512), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_solution_assignment_id'), 'solution', ['assignment_id'], unique=False)
    op.create_index(op.f('ix_solution_student_id'), 'solution', ['student_id'], unique=False)
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'HALF_DAY', 'PRESENT', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_attendance_student_id'), 'student_attendance', ['student_id'], unique=False)
    op.create_table('teacher_attendance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('ABSENT', 'HALF_DAY', 'PRESENT', name='status'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teacher_attendance_teacher_id'), 'teacher_attendance', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_attendance_teacher_id'), table_name='teacher_attendance')
    op.drop_table('teacher_attendance')
    op.drop_index(op.f('ix_student_attendance_student_id'), table_name='student_attendance')
    op.drop_table('student_attendance')
    op.drop_index(op.f('ix_solution_student_id'), table_name='solution')
    op.drop_index(op.f('ix_solution_assignment_id'), table_name='solution')
    op.drop_table('solution')
    op.drop_index(op.f('ix_fee_transaction_student_id'), table_name='fee_transaction')
    op.drop_table('fee_transaction')
    op.drop_table('student')
    op.drop_index(op.f('ix_teacher_time_table_teacher_id'), table_name='teacher_time_table')
    op.drop_table('teacher_time_table')
    op.drop_index(op.f('ix_section_numeric'), table_name='section')
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.drop_table('section')
    op.drop_table('teacher')
    op.drop_table('library')
    op.drop_table('fee_structure')
    op.drop_table('enquiry')
    op.drop_index(op.f('ix_classes_numeric'), table_name='classes')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_table('classes')
    op.drop_index(op.f('ix_bus_route_bus_id'), table_name='bus_route')
    op.drop_table('bus_route')
    op.drop_table('assignment')
    # ### end Alembic commands ###
