"""added col from student

Revision ID: e6cf3ab074fc
Revises: fff18f56135d
Create Date: 2021-01-13 09:16:48.380197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6cf3ab074fc'
down_revision = 'fff18f56135d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('student', sa.Column('mobile_no', sa.String(length=32), nullable=False))
    op.add_column('student', sa.Column('password', sa.String(length=512), nullable=False))
    op.add_column('student', sa.Column('username', sa.String(length=512), nullable=False))
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    op.create_index(op.f('ix_student_mobile_no'), 'student', ['mobile_no'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_mobile_no'), table_name='student')
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.drop_column('student', 'username')
    op.drop_column('student', 'password')
    op.drop_column('student', 'mobile_no')
    op.drop_column('student', 'email')
    # ### end Alembic commands ###
