"""modified student

Revision ID: f768337fc82a
Revises: 407bfff6f49d
Create Date: 2021-01-15 23:28:48.771869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f768337fc82a'
down_revision = '407bfff6f49d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('migration', sa.String(length=512), nullable=True))
    op.add_column('student', sa.Column('photo', sa.String(length=512), nullable=True))
    op.add_column('student', sa.Column('tc', sa.String(length=512), nullable=True))
    op.drop_column('student', 'tc_path')
    op.drop_column('student', 'migration_path')
    op.drop_column('student', 'photo_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('photo_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('migration_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('tc_path', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('student', 'tc')
    op.drop_column('student', 'photo')
    op.drop_column('student', 'migration')
    # ### end Alembic commands ###
