"""remove user pass 2

Revision ID: f94be9f9de02
Revises: 4fb761978ed9
Create Date: 2021-01-12 09:47:56.638308

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f94be9f9de02'
down_revision = '4fb761978ed9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher', 'password')
    op.drop_column('teacher', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher', sa.Column('username', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('teacher', sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
