"""removed col from student

Revision ID: fff18f56135d
Revises: 3cd1dbc6c4ba
Create Date: 2021-01-13 09:16:16.462389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fff18f56135d'
down_revision = '3cd1dbc6c4ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_student_mobile_no', table_name='student')
    op.drop_column('student', 'password')
    op.drop_column('student', 'mobile_no')
    op.drop_column('student', 'username')
    op.drop_column('student', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('student', sa.Column('username', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('mobile_no', sa.VARCHAR(length=32), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('password', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.create_index('ix_student_mobile_no', 'student', ['mobile_no'], unique=True)
    # ### end Alembic commands ###
